name: github-mirror
on: push
jobs:
  push-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Push to GitHub
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EkiciLP/Marinara.git
          ssh_private_key:
            ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
